from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, Integer, String
from sqlalchemy.orm import Mapped, mapped_column


from app.database import Base


class VisitLog(Base):
    """One row per page view across the site.

    Logged-in visits attribute via user_id; anonymous visits attribute via
    a random session_id the client generates and persists in localStorage
    so unique-visitor counts stay accurate without storing IPs.

    Geo fields (country / region / city) come from Vercel's edge-injected
    request headers — free, no external API, no IP storage on our side.
    """

    __tablename__ = "visit_logs"
    __table_args__ = (
        Index("ix_visit_logs_created", "created_at"),
        Index("ix_visit_logs_user_created", "user_id", "created_at"),
        Index("ix_visit_logs_country_created", "country", "created_at"),
        Index("ix_visit_logs_session_created", "session_id", "created_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    user_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    """Null when the visitor wasn't signed in."""

    session_id: Mapped[str] = mapped_column(String(64), nullable=False)
    """Random UUID generated by the client and persisted in localStorage.
    Lets us count unique anonymous visitors without storing IPs."""

    path: Mapped[str] = mapped_column(String(512), nullable=False)
    """Pathname including leading slash, e.g. '/cards/me2-125' or '/portfolio'."""

    country: Mapped[str | None] = mapped_column(String(2), nullable=True)
    """ISO 3166-1 alpha-2 country code from Vercel's x-vercel-ip-country
    header. None if Vercel couldn't resolve (local dev, certain proxies)."""

    region: Mapped[str | None] = mapped_column(String(64), nullable=True)
    """Subdivision (state/province) from x-vercel-ip-country-region."""

    city: Mapped[str | None] = mapped_column(String(96), nullable=True)
    """City from x-vercel-ip-city."""

    referrer: Mapped[str | None] = mapped_column(String(512), nullable=True)
    """document.referrer captured client-side. Trimmed to 512 chars."""

    device: Mapped[str | None] = mapped_column(String(16), nullable=True)
    """Coarse device class: 'mobile' / 'desktop' / 'tablet' / 'bot'.
    Derived client-side from the UA so we don't store full UA strings."""

    bot_name: Mapped[str | None] = mapped_column(String(64), nullable=True)
    """Known-bot identifier extracted server-side from the User-Agent
    header (e.g. 'Googlebot', 'GPTBot', 'AhrefsBot'). Only whitelisted
    bot names are stored — full UA strings never touch disk to preserve
    visitor privacy. None for human visits and unknown UAs."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )
